### ISSUE TITLE
Request: Run all samples at once

### ISSUE THREAD

**Issue by ericchaves** [mway-io/The-M-Project-Sample-Apps#3]
Hi guys,

It would be great if we could execute espresso server from the root of M-Project-Samples to access the apps by just navigating into the directories instead of having to call espresso server for each app.

Cheers,

Eric

**Comment by sebastianwerler** [comment]
Hey Eric,

thx for your issue. 

Your feature request is in some parts opposed to the way the espresso server works. When accessing e.g. http://127.0.0.1:8000/MyApp Espresso builds MyApp on the fly with all configurations made in config.json, like proxy settings, optimization options etc. 

This means accessing the resource "MyApp" on 127.0.0.1:8000 starts a dynamic task instead of just shipping static files. For sure, Espresso could be rewritten to dynamically search for folders with the name "MyApp" or whatever you pass as a path, but the effort for rewriting it, isn't small and one of the few situation you need it is for the The-M-Project-Samples Collection.

What you can do to ease up your process is to use espresso with the "-d" option to specify a directory. This saves you from jumping in and out of each directory.

Another thing you can do is to build all samples (maybe we can do it and have the latest builds published in the sample app repository) and copy the builds in one folder and direct your apache on this directory. This would be the behaviour you'd like to see for Espresso. For sure, apps needing a proxy setting (e.g. the Twitter app) will not run out-of-the-box without setting a proxy in your Apache config.

Best regards
Sebastian
